apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-proxy
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://ag-notifikasjon-proxy.dev.nav.no/
  liveness:
    path: /internal/alive
    initialDelay: 20
  readiness:
    path: /internal/ready
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/metrics
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: PROXY_LOG_LEVEL
      value: 'debug'
    - name: BRUKER_API_URL
      value: 'http://notifikasjon-bruker-api.fager.svc.cluster.local'
  accessPolicy:
    outbound:
      rules:
        - application: notifikasjon-bruker-api
