name: deploy dev manual
on:
  workflow_dispatch:

jobs:
  dev-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Login to GitHub Package Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: proxy-server
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/arbeidsgiver-notifikasjon-proxy:${{ github.sha }}
            ghcr.io/${{ github.repository }}/arbeidsgiver-notifikasjon-proxy:latest
          cache-from: type=registry,ref=${{ github.repository }}/arbeidsgiver-notifikasjon-proxy:latest
          cache-to: type=inline

      - uses: nais/deploy/actions/deploy@v1
        name: "deploy dev ${{ github.ref }}"
        env:
          IMAGE: ghcr.io/${{ github.repository }}/arbeidsgiver-notifikasjon-proxy:${{ github.sha }}
          REF: ${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml

