name: deploy dev manual
on:
  workflow_dispatch:

jobs:
  dev-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        name: "deploy dev ${{ github.ref }}"
        env:
          IMAGE: ghcr.io/${{ github.repository }}/arbeidsgiver-notifikasjon-proxy:${{ github.sha }}
          REF: ${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml

